#!/bin/bash

if [[ -d dist ]]; then
  rm -rf dist;
fi

mkdir dist;

./node_modules/babel-cli/bin/babel.js ./src/image-gallery.js --compact true | ./node_modules/uglify-js/bin/uglifyjs -o ./dist/image-gallery.js
./node_modules/node-sass/bin/node-sass ./src/image-gallery.scss --output-style compressed > ./dist/image-gallery.css
